### ISSUE TITLE
Enable Travis-CI for this Project to Confirm Tests are Passing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-ecto-append-only-log-example#3]
Tests for #2 (Daniel's PR) currently _pass_ on my Localhost:
![image](https://user-images.githubusercontent.com/194400/45836347-e429c500-bd0c-11e8-8646-d51812d5f96c.png)

But we cannot "_know_" this without checking out the branch and running the tests on `localhost` ...

## Todo

+ [x] Using https://github.com/dwyl/phoenix-ecto-encryption-example/blob/master/.travis.yml as an example, create a `.travis.yml` file for this project.
  + [x] create `append_only` user on Travis-CI before attempting to run tests 
  see: https://github.com/dwyl/phoenix-ecto-append-only-log-example/issues/3#issuecomment-423412835
+ [x] Add any necessary lines to `mix.exs` so that we can run coverage using `:excoveralls`
  + [x] using example: https://github.com/dwyl/phoenix-ecto-encryption-example/blob/master/mix.exs#L50
+ [x] Enable the project on Travis-CI.org so tests are run on every commit/push.

Thanks! 👍

**Comment by nelsonic** [comment]
Got `mix cover` working on `localhost` on `tutorial` branch:
![image](https://user-images.githubusercontent.com/194400/45836912-55b64300-bd0e-11e8-8e30-b536a6247379.png)

**Comment by nelsonic** [comment]
https://travis-ci.org/profile/dwyl enabled:
![image](https://user-images.githubusercontent.com/194400/45837175-002e6600-bd0f-11e8-9540-f807cc6e4194.png)

**Comment by nelsonic** [comment]
Build fails on Travis-CI because it is expecting a `"append_only"` Postgres user to exist:
https://travis-ci.org/dwyl/phoenix-ecto-append-only-log-example/builds/431146775#L604
![image](https://user-images.githubusercontent.com/194400/45861046-d145dd80-bd6a-11e8-80b5-5b78a211be99.png)
So we need to _create_ the user on Travis-CI _before_ attempting to run the tests.

**Comment by nelsonic** [comment]
Thanks to: https://stackoverflow.com/questions/42177055/how-to-set-up-travis-ci-and-postgresql-using-custom-db-credentials
![image](https://user-images.githubusercontent.com/194400/45861268-ee2ee080-bd6b-11e8-94c2-6bda29320338.png)

it's relatively easy to add a `before_script:` to the `.travis.yml` file.
Trying it now:
```yml
before_script:
  - psql -c "CREATE USER append_only WITH PASSWORD 'postgres';" -U postgres
  - psql -c "ALTER USER append_only CREATEDB;" -U postgres
```

**Comment by nelsonic** [comment]
Build passing: https://travis-ci.org/dwyl/phoenix-ecto-append-only-log-example/builds/431336390
![image](https://user-images.githubusercontent.com/194400/45861474-a9ec1200-bd64-11e8-9790-6acebcb16176.png)

We can work on improving the coverage _after_ the tutorial is more complete. 👍
